### ISSUE TITLE
Failed building JavaScript bundle

### ISSUE THREAD

**Issue by lunvjp** [ChickenKyiv/recipe-app-react-native#144]
# Description/Steps to reproduce
STEP 1: Clone this repo
STEP 2: Get this thing.
![image](https://user-images.githubusercontent.com/23715737/45819134-cc067580-bd0d-11e8-9334-55f839fccaaa.png)
=======================
Until now, I still don't know How to deal with this

# Expected result
Run successfully.

# Additional information
- Maybe because we've just updated React to 16.5.2

**Comment by atherdon** [comment]
can you try to create a clean RN project in a separated folder and try to make a bundle? If it'll work  - then it's not a React
i think we have a similar problems here, with expo and stuff

**Comment by atherdon** [comment]
try to run `npm install`, because maybe after pull requests - you have an outdated version of local modules

**Comment by lunvjp** [comment]
Thanks. It has been resolved with delete `node_modules` and run `yarn install`

**Comment by atherdon** [comment]
yarn and npm a good tools, so you don't need to delete `node_modules` every time when you get a conflict code changes. just `yarn install` will redo all things for you.

**Comment by atherdon** [comment]
btw, in order to have more training for you, related to all this PR things, i merged a few updated modules into master. please grab them too :)
