### ISSUE TITLE
add link to expo

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/recipe-app-react-native#162]
# Description/Steps to reproduce
> I spotted a few components that need to be created in the Todo column of the Trello board. 
However, I can't load the app in snack.expo.io through its github 
repository. It states the following: 
![image](https://user-images.githubusercontent.com/1469198/46571132-5be82880-c978-11e8-8274-37cdee6fe75d.png)
So how can I load the app to see it live? 
@lunvjp can you assist?

# Expected result

# Additional information

**Comment by lunvjp** [comment]
That's weird. it works with my test link: https://github.com/lunvjp/test-snack-import.git
I need to debug it for a while

**Comment by SofianeDjellouli** [comment]
@lunvjp It doesn't work with your link either
![image](https://user-images.githubusercontent.com/38258952/46579153-3c024480-ca0c-11e8-9472-f4a31c8da9a5.png)

**Comment by lunvjp** [comment]
Oh..Let me check it.

**Comment by lunvjp** [comment]
it works well with me. 
https://snack.expo.io/@git/github.com/lunvjp/test-snack-import
That's weird.

**Comment by atherdon** [comment]
Guys, what do you think if we'll make a new setup? i think this can help us.
tell me what you think

**Comment by lunvjp** [comment]
It's no problem from me. Let me updated about it. What kinds of new setup should we make for now?

**Comment by atherdon** [comment]
@SofianeDjellouli what do you think is the easiest way to solve this issue?

**Comment by atherdon** [comment]
i think we should also connect @Naaman-Saif to this conversation

**Comment by atherdon** [comment]
got it. it's my fault - I usually like to keep dependencies updated to the
latest versions. can you fix it?

**Comment by Naaman-Saif** [comment]
Hi Sofiane. Thank you so much. I saw this earlier but thought it was only me. I'll get this done soon.

**Comment by atherdon** [comment]
@SofianeDjellouli please update a Readme, so anyone will know about this link.

Btw, if you think we should reoder or reorganize structure - discuss this with @Naaman-Saif and decide what to do. i'm sure @lunvjp will be ok with this plan

**Comment by SofianeDjellouli** [comment]
[PR Update README.md with Snack Expo link #164](https://github.com/ChickenKyiv/recipe-app-react-native/pull/164)

**Comment by atherdon** [comment]
PR merged

**Comment by SofianeDjellouli** [comment]
@atherdon thanks 
@Naaman-Saif 
PR with proper versions: https://github.com/ChickenKyiv/recipe-app-react-native/pull/165

**Comment by atherdon** [comment]
merged too. i think i'll be more careful with updating packages for this
project - don't want to break it again.

**Comment by atherdon** [comment]
ok, i think this issue can be closed
